version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/docker/initdb:/docker-entrypoint-initdb.d:ro
    # For security, avoid exposing Postgres to the public host unless you need it
    # ports:
    #   - "${POSTGRES_HOST_PORT:-5432}:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      PORT: ${BACKEND_PORT:-4000}
    depends_on:
      - db
    ports:
      - "${HOST_BACKEND_PORT:-4000}:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HOST_FRONTEND_PORT:-80}:80"
    depends_on:
      - backend

volumes:
  db-data:
